publisher:
	g++ -o publisher publisher.cpp -g -Wall -std=c++11 -L/usr/local/lib -I/usr/local -lzmq

subscriber:
	g++ -o subscriber subscriber.cpp -g -Wall -std=c++11 -L/usr/local/lib -I/usr/local -lzmq	

clean:
	$(RM) *.o *~ publisher subscriber
